### ISSUE TITLE
Some deprecated and missing dependency libraries for ubuntu users

### ISSUE THREAD

**Issue by mascot6699** [fossevents/fossevents.in#27]
I was trying to setup the project today and found the following problems
_libtiff4-dev_ and _liblcms1-dev_ have been deprecated in favour of _libtiff5-dev_ and _liblcms2-dev_

Also there is missing dependency library to install _lxml_
for these we need to add _libxml2-dev_ and  _libxslt1-dev_

I will be happy to update the ubuntu.apt file accordingly and create a PR.

**Comment by mascot6699** [comment]
Related snapshot

![deprecated dependency libraries](https://cloud.githubusercontent.com/assets/3908832/10415150/30640b72-700a-11e5-9264-4bf21353f314.png)

and for lxml issue read [here](http://stackoverflow.com/a/6504860/2392921)

**Comment by theskumar** [comment]
Thanks for reporting and solving as well. :+1:
