### ISSUE TITLE
Add PyCon Pune 2017 to fossevents.in

### ISSUE THREAD

**Issue by shakthimaan** [fossevents/fossevents.in#44]
Greetings!

Request you to kindly add PyCon Pune 2017 to fossevents.in.

  https://pune.pycon.org/

Thanks!

**Comment by satyaakam** [comment]
Why request when you can help yourself ?! Well the whole idea of the site is to Crowdsource.There is a submit an event link right at the top besides the Logo.

hth
-Satya

**Comment by shakthimaan** [comment]
The first thing that struck me with the site were the list of events. The link didn't strike me initially.

Will ask the organizers to submit the necessary details. Thanks for the quick resolution.
