### ISSUE TITLE
RSS Feeds For All the Event Listings. 

### ISSUE THREAD

**Issue by aniketmaithani** [fossevents/fossevents.in#6]
I think we should also have support for RSS Feeds for all the listed events. If the events are categorized we should have feed per category also. I would be happy to take this job.

**Comment by theskumar** [comment]
Implementation can be done via https://docs.djangoproject.com/en/1.8/ref/contrib/syndication/

This doesn't get any milestone yet.

This work can be started as soon as possible. The next step would be decide on the all the exposed feed url patterns and decide, the length on the feed as rss don't have pagination.

**Comment by Kushagra343** [comment]
made basic implementation of rss feed in  #19 , what changes are required on url patterns and length of the feed

**Comment by aniketmaithani** [comment]
@theskumar I have submitted PR #26 for this. My bad I haven't gone through the whole `issues`. But I guess for Pagination we can show `TOP 10` events.
